### ISSUE TITLE
Fill TimeSeries with zero where there are no events

### ISSUE THREAD

**Issue by camflan** [esnet/pond#109]
Trying to improve performance of our timeseries api and I've testing pypond, pond.js and react-timeseries-charts as a means of doing so.

We have data coming in off of sensors that we want to graph, the issue is that the sensors data is filtered, and we're not getting any events when there is no data. Right now we manually build a time range and aggregate the stats ourselves before shipping it to our graphing library. By simply swapping our legacy wire format to the pond TimeSeries format, we get a graph that looks great.
![screen shot 2018-03-23 at 11 03 21 am](https://user-images.githubusercontent.com/27292/37841055-b1c3e712-2e8c-11e8-96d3-48625d810ef3.png)

However, by shipping a TimeSeries without manually constructing the time range, we get a graph like so,
![screen shot 2018-03-23 at 11 03 14 am](https://user-images.githubusercontent.com/27292/37841092-ce108e7a-2e8c-11e8-838e-5cfb7b2821d6.png)

Maybe this is a react-timeseries-charts question -- but I've been unable to construct a TimeSeries that will assume 0 where we don't have timestamped data. I've tried some Pipelines, and all the Fill, Align, and Rollups that I can think of. Is there a way to tell react-timeseries-charts to drop these gaps to 0? Or, can I construct the TimeSeries I want in Pond and let react-timeseries-charts do what it does best - graph the given pond.js TimeSeries?

**Comment by pjm17971** [comment]
If I'm understanding correctly, you want to get `fill` to work. It lets you specify a period which data should exist for and then it will fill with 0s (one of the options). If you want to go the route of a PR, I've also thought it would be nice if Pond had a split function you could call on a TimeSeries and it would return a list of TimeSeries. There's some options as to how that would be useful. The ones that occur to me are a sequence of bad (undefined, null, NaN) or a duration of no values. Another alternative is for AreaCharts to support splitting up based on gaps rather than just drawing across them. The LineChart supports that.

**Comment by camflan** [comment]
@pjm17971 Yes, I had assumed that Fill would work in this fashion. Because it wasn't, I assumed that the intention of Fill was only to transform `null`, `NaN`, etc to 0 or an interpolated value.

I'll take a look at fixing this, thanks!
