### ISSUE TITLE
RollUp timestamps are not timestamps

### ISSUE THREAD

**Issue by ciarancourtney** [esnet/pond#119]
After rollUp aggregation the timestamps are some sort of description of the the aggregation method i.e. `1d-1234`  I'm guessing '1d' is the duration and 1234 is an index. Would it be possible to have an option to output a rolled-up unix timestamp i.e. midnight if daily, midnight Sunday if weekly, 1st of month if monthly and so.

I understand this brings up the issue of what timestamp should represent an aggregated time period.

* Should timestamp be at start or end of time period
* Sunday/Monday is start of week
* How timezones are handled, are unix timestamps assumed to naively match localtime or are they strictly UTC

**Comment by pjm17971** [comment]
Are you using Pond 1.0 alpha or the 0.8.x code?

In either case, this is intentional. As you say the timestamp for the aggregated time period is application specific, which is exactly why it's represented like that. Also, the timeseries charts code can display certain types of charts (e.g. barcharts) from that representation.

If you are using the 1.0 code, then chain a remapKey() call to the rollup.
```
timeseries.fixedWindowRollup(options).mapKeys(index => time(index.asTimerange().mid()))
```
If you are using the 0.8 code then there's an option on fixedWindowRollup to output times rather than indexes.
