### ISSUE TITLE
How to use a Rolling/Sliding Window

### ISSUE THREAD

**Issue by omidkrad** [esnet/pond#167]
Hi, I'm trying to get basic functionality of a rolling/sliding window. From the docs I couldn't figure exactly how to use it, but I'm trying to have a window of a specific size, let's say 10 minutes, that I feed to it an event on a variable frequency, that can be between few seconds to few minutes, and calculate different indicators on it like moving average, etc. Can you please point me to an example I can start from? 

Also Pond seems to be very versatile, would you recommend pond for a simple use case like the one above, or do you know of any other, maybe more limited or simplistic time series library that you can recommend? Thank you for your help.

**Comment by pjm17971** [comment]
Sliding windows mostly relate to streaming events. 

See this test here:
https://github.com/esnet/pond/blob/2a9e80d895f479adc0c14d0496a4085f3f2904d7/packages/pond/tests/stream.test.ts#L313

The windows have a fixed size, like 10 min, and a period, like 1 min. They don't move continuously, so I'm not sure if it fits your use case exactly. This is a common approach to sliding windows though because it creates fixed buckets that you can aggregate. We don't use sliding windows (or actually any of the pond streaming constructs) internally anymore, so ymmv.

The possibilities for how you might want to manage incoming events like that are actually quite varied, so we've mostly moved away from trying to tackle this ourselves, especially as our events/s grew. I don't really know about other libraries, especially on the simpler side of things, but we use Apache Beam (Google Dataflow) now for anything serious, leaving Pond to mostly do work on the browser where appropriate.
