### ISSUE TITLE
How to append new events?

### ISSUE THREAD

**Issue by johnyesberg** [esnet/pond#176]
If I'm visualising a TimeSeries in my browser, and new data points/events arrive, is there a recommended way to create a new TimeSeries from the existing one plus the new events?

**Comment by Mike-Dax** [comment]
This is roughly what we do.

```tsx
    const timeSeries = new TimeSeries({
      events: Immutable.List(),
    })

    const collection = timeSeries.collection()

    const newCollection = collection.addEvent(event)

    timeSeries = timeSeries.setCollection(newCollection)
```

**Comment by johnyesberg** [comment]
Thanks @Mike-Dax 
I guess another option would be to create a new timeSeries from the new event, and then use 
 something like

    updatedTimeSeries = TimeSeries.timeSeriesListMerge({
        name: "traffic",
        seriesList: [previousTimeSeries, timeSeriesContainingNewEvent]
    });

**Comment by Mike-Dax** [comment]
That will be less performant, since it will generate an entirely new list of events, then add that list of events to an empty Immutable List, instead of just appending one event to the already created list.

In our fork of pond we added this method to SortedCollection in order to avoid re-sorting the list every time an event was added, given we guarantee temporal ordering.

```tsx
  /**
   * Appends a new `Event` to the `SortedCollection`, returning a new `SortedCollection`
   * containing that `Event`. This function bypasses all sorting with the assumption that
   * the new `Event` is guaranteed to be after previous ones. Deduplication is not supported.
   */
  public addEventGuaranteedStillChronological(
    event: Event<T>,
  ): SortedCollection<T> {
    const k = event.getKey().toString()

    let events = this._events
    let e = event // Our event to be added
    let indicies: Immutable.Set<number> = this._keyMap.has(k)
      ? this._keyMap.get(k)
      : Immutable.Set<number>()

    // Add the new event to our event list
    events = events.push(e)

    // Call the post add hook to give sub-classes a chance to modify
    // the event list. If they do, then we'll rebuild the keyMap.
    let newKeyMap = this._keyMap

    indicies = indicies.add(events.size - 1)
    newKeyMap = this._keyMap.set(k, indicies)

    return this.clone(events, newKeyMap)
  }
```

Feel free to use that if you like, replacing the `collection.addEvent(event)` call with `collection.addEventGuaranteedStillChronological(event)`

**Comment by johnyesberg** [comment]
Thanks @Mike-Dax - I appreciate your experience.
