### ISSUE TITLE
Past-Dependent Functions

### ISSUE THREAD

**Issue by isaacsanders** [esnet/pond#49]
Hey all,

I was wondering if there existed a mechanism for reductions (past-dependent functions) on pipelines.

Is it the case that:
- The functionality exists
- The functionality doesn't exist, but the feature is desired
- The functionality doesn't exist, and is not desired

**Comment by pjm17971** [comment]
So a simple example would be sum the value of all the events? I think that would come under the second category: doesn't exist, desired. A lot of applications probably care more about sliding windows, rather than accumulating for all time. So I think there's also the implementation of that.

For for the simpler non-window version of this, you could probably follow the [taker](https://github.com/esnet/pond/blob/master/src/pond/lib/processors/taker.js#L58) processor and how that is implemented. It has a sense of history because it will only take n items. In this case I'd image you'd add a reducer. You'd initialize it with tuple and a reduction function. Internally it would maintain the accumulated state per window and group by key (as seen in the taker). For each new event it would run the reduction function on the event, passing in the event and the keys accumulated state. The result would be a new event containing the tuple which it would emit. Seems fairly straight forward. If we're on the same page, feel free to offer up a PR. I can help further if you need it.

**Comment by isaacsanders** [comment]
I have looked at the documentation again, and wouldn't, so a daily running sum, a Pipeline, windowed by one day, emitting on each event, and summing have a running sum of sorts? It appears, another example I have thought of, moving average, is implemented in the documentation thusly.

**Comment by isaacsanders** [comment]
I would be potentially interested in working on the actual feature you described, because i suppose there are different cases than the one I have so far.

**Comment by pjm17971** [comment]
Yes, you can do windowing, currently only fixed windowing, for any window you can specify with the notation used "5m", "1h", "1d" etc.

Fixed windows are always aligned to UTC time, and don't overlap. i.e. you can do Monday,Tuesday, Wednesday... averages, for example, but you can't do "the last 24 hours" from now. That would be a sliding window. You can use the `emitOn` to control how often you get an event out. Options being every time an event enters (so you'd get many outputs which would be partial results), or every time a fixed window is discard (events move onto the next fixed window). Depends on your application. Also note that if you have a fixed timeseries, rather than an unbounded stream of events, there's convenience functions on the TimeSeries itself to do rollups (that use the pipelines internally).

The reducer described above is a reasonable feature, because it lets you do quick counts etc. However, if I was going to assign priorities for streaming data I'd go with:
1) sliding windows (#37)
2) better triggering (for example allowing for late data)
3) de-duping repeated data (I'm working towards that one)
4) better abstraction between the pipeline DAG and the actual execution graph which would allow us to build execution nodes that could take advantage of multiple cores

This would mean you could use pond in a situation where you are able to handle an incoming stream on a single machine. If your needs go beyond that, there are other more complicated solutions.

**Comment by pjm17971** [comment]
Past dependent functions in the form of a `reducer` processor, are now in 1.0.0 alpha 2. 
```
const source = stream()
    .reduce({
        count: 1,
        accumulator: event(time(), Immutable.Map({ total: 0 })),
        iteratee(accumulation, eventList) {
            const current = eventList.get(0);
            const total = accumulation.get("total") + current.get("count");
            return event(time(current.timestamp()), Immutable.Map({ total }));
        }
    })
    .output((e: Event) => console.log("Running total:", e.toString()) );

// Add Events into the source...
events.forEach(e => source.addEvent(e));
```
