### ISSUE TITLE
When you aggregate rollups and an event value equals 0, it will throw chart errors.

### ISSUE THREAD

**Issue by yrokhlin** [esnet/pond#69]
I was creating some rollups, and I aggregated the data using `avg()` and I noticed that the `BarChart` started throwing `<rect>` and `NaN` errors when displaying the aggregated `TimeSeries`. I had to run `.clean()` on all the values to get the errors to go away.. is this intended behavior?

**Comment by pjm17971** [comment]
Yes and no I suppose.

There's a few things here:
 - Having the `BarChart` actually blow up is probably not desired. Can you add an issue in the charts code with a sample of the problematic series that is being passed into the BarChart?
 - The aggregation in Pond is controlled in a number of ways. See the code here:
https://github.com/esnet/pond/blob/master/src/pond/lib/base/functions.js#L20
This is supposed to be your friend, but...
 - It seems like those aren't being exported for the JS / npm package, so that's not helpful. If they were you could pass one of those into the `avg()` to clean the data during the aggregation.

The approach is that the library doesn't really know what you want to do about missing or NaN values and so these function are supposed to help with some common strategies. Thinking about it though, I think we only use them in Python.

**Comment by yrokhlin** [comment]
As soon as we finish up our current deployment I will dive back in this and look through it. Seriously appreciate the insight immensely.

**Comment by yrokhlin** [comment]
Hey `filter.keepMissing` completely did the trick, maybe possibly add this to documentation or make a special note??

It seems that an aggregated `average/max etc` of a value of 0 will break certain charts.
