### ISSUE TITLE
How to limit the size of internal collection of Pipeline ?

### ISSUE THREAD

**Issue by tech-a-go-go** [esnet/pond#78]
Hi there,

I would like to know how to limit the size of internal collection of Pipeline.
I'm sending events every second for 24/7 to my pipeline via Stream but I only need LAST 3 hours of data in it so I'm afraid of wasting the memory...

Is it impossible to specify something like keep only last ?? hours of data or any tips to work around ??

Cheers

**Comment by pjm17971** [comment]
Events you are adding to a Pipeline are processed though the pipeline one by one, so inherently there's no accumulation internally. At least, that is the case until you window, in which case each active window will accumulate within the range of that window. Also, some operations will keep a small buffer.

There's no current support for sliding windows (such as "last 3 hours"), though there maybe in the future. If you still want to use a pipeline (because you are using other functions like `align`, `fill`, etc), but still want a sliding window at the end, my best suggestion is to use a circle buffer. The react-timeseries-charts [realtime](https://github.com/esnet/react-timeseries-charts/blob/master/src/website/packages/charts/examples/realtime/Index.js) example does this.

```javascript
pipeline()
    .from(this.stream)
    .windowBy("5m")
    .emitOn("discard")
    .aggregate({
        value: { value: percentile(90) }
    })
    .to(EventOut, event => {
        circleBuffer.push(event);
    });
```

**Comment by tech-a-go-go** [comment]
Hi pjm,

Thanks a lot for your reply !

> so inherently there's no accumulation internally.
Oh, I see.
I thought there was. It's my mistake. sorry.

And also thank you for the snippet. That helped me out !!

Cheers

**Comment by tech-a-go-go** [comment]
Hi pjm,

Sorry, again.
I've checked the source code and found out that collector.js has a _collections variable in it.
It seems the elements of the variable lasts forever... which I'm afraid of wasting memory since my system runs 24/7. Is there a way to discard older ones of them ?

Actually, I'm not only afraid of wasting memory, but I'm getting so many events of old data which I don't need anymore.

This is a sample code which I want to let you know which data I need and which I don't.
I guess It's easier to understand by seeing a code than my explanation above.
```
'use strict';
const _ = require('lodash');
const moment = require('moment');
const TimeEvent = require('pondjs').TimeEvent;
const Pipeline = require('pondjs').Pipeline;
const Stream = require('pondjs').Stream;
const EventOut = require('pondjs').EventOut;
const last = require('pondjs').last;

class PipelineTest {
  constructor() {
    this.stream = new Stream();
    this.pipeline = Pipeline().from(this.stream)
          .windowBy('5m')
          .emitOn('eachEvent')
          .aggregate({pressure: {pressure: last()}})
          .to(EventOut, c => this.onPipelineEvent(c));
  }
  
  fire(evt) {
    this.stream.addEvent(evt);
    console.log();
  }

  onPipelineEvent(e) {
    console.log(
      moment(e.timestamp()).format('YYYY-MM-DD HH:mm:ss'),
      e.data().get('pressure')
    );
  }
}

const t = new PipelineTest();

let tm = moment('2017-08-07 00:04:58').valueOf();
let ev = new TimeEvent(tm, {pressure: 80});
t.fire(ev);

tm = moment('2017-08-07 00:04:59').valueOf();
ev = new TimeEvent(tm, {pressure: 95});
t.fire(ev);

tm = moment('2017-08-07 00:05:00').valueOf();
ev = new TimeEvent(tm, {pressure: 101});
t.fire(ev);

tm = moment('2017-08-07 00:05:01').valueOf();
ev = new TimeEvent(tm, {pressure: 99});
t.fire(ev);

tm = moment('2017-08-07 00:05:02').valueOf();
ev = new TimeEvent(tm, {pressure: 95});
t.fire(ev);

tm = moment('2017-08-07 00:09:59').valueOf();
ev = new TimeEvent(tm, {pressure: 96});
t.fire(ev);

tm = moment('2017-08-07 00:10:00').valueOf();
ev = new TimeEvent(tm, {pressure: 97});
t.fire(ev);

tm = moment('2017-08-07 00:10:01').valueOf();
ev = new TimeEvent(tm, {pressure: 98});
t.fire(ev);
```
The result and my comment (need or not) is as follows.
> node@docker:/server$ node test-pipeline.js
> 2017-08-07 00:00:00 80 <--- NEED
> 
> 2017-08-07 00:00:00 95  <--- NEED
> 
> 2017-08-07 00:00:00 95  <--- DON'T NEED since I already have.
> 2017-08-07 00:05:00 101 <--- NEED
> 
> 2017-08-07 00:00:00 95 <--- DON'T NEED since I already have.
> 2017-08-07 00:05:00 99  <--- NEED
> 
> 2017-08-07 00:00:00 95 <--- DON'T NEED since I already have.
> 2017-08-07 00:05:00 95 <--- NEED
> 
> 2017-08-07 00:00:00 95 <--- DON'T NEED since I already have.
> 2017-08-07 00:05:00 96 <--- NEED
> 
> 2017-08-07 00:00:00 95 <--- DON'T NEED since I already have.
> 2017-08-07 00:05:00 96 <--- DON'T NEED since I already have.
> 2017-08-07 00:10:00 97 <--- NEED
> 
> 2017-08-07 00:00:00 95 <--- DON'T NEED since I already have.
> 2017-08-07 00:05:00 96 <--- DON'T NEED since I already have.
> 2017-08-07 00:10:00 98 <--- NEED

The number of unneeded event will be 720 if I run my code for 24 hours.
I want to receive only the latest window event.
Is is possible to do that ? or any ways to discard older window data ??

Cheers

**Comment by pjm17971** [comment]
The `Collection` class does have a store of data in it as you say, but a pipeline as you are using it isn't using that. Pipelines can emit collections as an output, say one for each window, but that's not what you are doing. Collections also are the backing store for `TimeSeries`.

In a Pipeline, events are added to the top of the pipeline (`stream.addEvent()`) and are run through a chain of processors down to the output (`.to()`). Each processor is essentially fed events from above, processes them into 0, 1 or many new Events and emits them down to the next processor(s).

Are you actually seeing a run up of memory?

For the duplicates, possibly each window is emitting whenever a new Event is added to it, regardless of if the window is complete or not. If you use emit on discard (rather than per event), you will get output only when that window is done and won't have duplicates. It depends on if you want early (partial) results or not.

**Comment by tech-a-go-go** [comment]
> Are you actually seeing a run up of memory?
no, no, I mean I was just afraid if it was happening.

> If you use emit on discard, you will get output only when that window is done and won't have duplicates.
Yes, I want that and also want to get the latest event even though its window has not been done yet.
Is it possible ??

Let me explain in a simple way again...
I don't need duplicate events if those window has been done.
But I want duplicate events if those window has NOT been done yet.

Thanks

**Comment by pjm17971** [comment]
I'd just do what you're doing and use a map to de-duplicate.

A possibility that I've not tried is that you could branch the pipeline and have a per event output on one branch and a on discard output on the other. For how to fork the pipeline, see this [test](https://github.com/esnet/pond/blob/master/src/pond/lib/__tests__/pipeline.test.js#L250).

**Comment by tech-a-go-go** [comment]
I go for the former one  !!
Thank you so much !
